USE [PRODUCCION_BD]
GO

/****** Object: Table [dbo].[clusters] Script Date: 07/02/2017 12:36:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[clusters] (
    [name_clusterizacion]                                VARCHAR (50)   NOT NULL,
    [distancia]                                          VARCHAR (3)    NOT NULL,
    [num_apuestas_futbol_totales]                        INT            NULL,
    [num_apuestas_baloncesto_totales]                    INT            NULL,
    [num_apuestas_tenis_totales]                         INT            NULL,
    [num_apuestas_voleibol_totales]                      INT            NULL,
    [num_apuestas_beisbol_totales]                       INT            NULL,
    [num_apuestas_balonmano_totales]                     INT            NULL,
    [num_apuestas_rugby_totales]                         INT            NULL,
    [num_apuestas_futbol_americano_totales]              INT            NULL,
    [num_apuestas_mejoraTuLinea_totales]                 INT            NULL,
    [num_apuestas_galgos_totales]                        INT            NULL,
    [num_apuestas_caballos_totales]                      INT            NULL,
    [num_apuestas_artes_marciales_totales]               INT            NULL,
    [num_apuestas_boxeo_totales]                         INT            NULL,
    [num_apuestas_dardos_totales]                        INT            NULL,
    [num_apuestas_esports_totales]                       INT            NULL,
    [num_apuestas_hockey_totales]                        INT            NULL,
    [num_apuestas_loteria_totales]                       INT            NULL,
    [num_apuestas_politica_totales]                      INT            NULL,
    [name_cluster]                                       VARCHAR (50)   NOT NULL,
    [medioide]                                           VARCHAR (1100) NOT NULL,
    [num_sesiones_cluster]                               INT            NULL,
    [num_tickets_cerrados_cluster]                       INT            NULL,
    [ratio_tickets_cerrados_sesiones_cluster]            VARCHAR (10)   NULL,
    [ratio_tickets_cerrados_sesiones_apostantes_cluster] VARCHAR (10)   NULL,
    [num_sesiones_apostantes_cluster]                    INT            NULL,
    [ratio_sesiones_apostantes_cluster]                  VARCHAR (10)   NULL,
    [ratio_sesiones_logadas_cluster]                     VARCHAR (10)   NULL,
    [num_pasos_cluster]                                  VARCHAR (10)   NULL,
    [ratio_apuestas_tickets_cerrados_cluster]            VARCHAR (10)   NULL,
    [num_apuestas_futbol_cluster]                        INT            NULL,
    [ratio_apuestas_futbol_cluster]                      VARCHAR (10)   NULL,
    [ratio_apuestas_futbol_total]                        VARCHAR (10)   NULL,
    [num_visitas_futbol_cluster]                         INT            NULL,
    [ratio_visitas_futbol_cluster]                       VARCHAR (10)   NULL,
    [num_apuestas_baloncesto_cluster]                    INT            NULL,
    [ratio_apuestas_baloncesto_cluster]                  VARCHAR (10)   NULL,
    [ratio_apuestas_baloncesto_total]                    VARCHAR (10)   NULL,
    [num_visitas_baloncesto_cluster]                     INT            NULL,
    [ratio_visitas_baloncesto_cluster]                   VARCHAR (10)   NULL,
    [num_apuestas_tenis_cluster]                         INT            NULL,
    [ratio_apuestas_tenis_cluster]                       VARCHAR (10)   NULL,
    [ratio_apuestas_tenis_total]                         VARCHAR (10)   NULL,
    [num_visitas_tenis_cluster]                          INT            NULL,
    [ratio_visitas_tenis_cluster]                        VARCHAR (10)   NULL,
    [num_apuestas_voleibol_cluster]                      INT            NULL,
    [ratio_apuestas_voleibol_cluster]                    VARCHAR (10)   NULL,
    [ratio_apuestas_voleibol_total]                      VARCHAR (10)   NULL,
    [num_visitas_voleibol_cluster]                       INT            NULL,
    [ratio_visitas_voleibol_cluster]                     VARCHAR (10)   NULL,
    [num_apuestas_beisbol_cluster]                       INT            NULL,
    [ratio_apuestas_beisbol_cluster]                     VARCHAR (10)   NULL,
    [ratio_apuestas_beisbol_total]                       VARCHAR (10)   NULL,
    [num_visitas_beisbol_cluster]                        INT            NULL,
    [ratio_visitas_beisbol_cluster]                      VARCHAR (10)   NULL,
    [num_apuestas_balonmano_cluster]                     INT            NULL,
    [ratio_apuestas_balonmano_cluster]                   VARCHAR (10)   NULL,
    [ratio_apuestas_balonmano_total]                     VARCHAR (10)   NULL,
    [num_visitas_balonmano_cluster]                      INT            NULL,
    [ratio_visitas_balonmano_cluster]                    VARCHAR (10)   NULL,
    [num_apuestas_rugby_cluster]                         INT            NULL,
    [ratio_apuestas_rugby_cluster]                       VARCHAR (10)   NULL,
    [ratio_apuestas_rugby_total]                         VARCHAR (10)   NULL,
    [num_visitas_rugby_cluster]                          INT            NULL,
    [ratio_visitas_rugby_cluster]                        VARCHAR (10)   NULL,
    [num_apuestas_futbol_americano_cluster]              INT            NULL,
    [ratio_apuestas_futbol_americano_cluster]            VARCHAR (10)   NULL,
    [ratio_apuestas_futbol_americano_total]              VARCHAR (10)   NULL,
    [num_visitas_futbol_americano_cluster]               INT            NULL,
    [ratio_visitas_futbol_americano_cluster]             VARCHAR (10)   NULL,
    [num_apuestas_mejoraTuLinea_cluster]                 INT            NULL,
    [ratio_apuestas_mejoraTuLinea_cluster]               VARCHAR (10)   NULL,
    [ratio_apuestas_mejoraTuLinea_total]                 VARCHAR (10)   NULL,
    [num_visitas_mejoraTuLinea_cluster]                  INT            NULL,
    [ratio_visitas_mejoraTuLinea_cluster]                VARCHAR (10)   NULL,
    [num_apuestas_galgos_cluster]                        INT            NULL,
    [ratio_apuestas_galgos_cluster]                      VARCHAR (10)   NULL,
    [ratio_apuestas_galgos_total]                        VARCHAR (10)   NULL,
    [num_visitas_galgos_cluster]                         INT            NULL,
    [ratio_visitas_galgos_cluster]                       VARCHAR (10)   NULL,
    [num_apuestas_caballos_cluster]                      INT            NULL,
    [ratio_apuestas_caballos_cluster]                    VARCHAR (10)   NULL,
    [ratio_apuestas_caballos_total]                      VARCHAR (10)   NULL,
    [num_visitas_caballos_cluster]                       INT            NULL,
    [ratio_visitas_caballos_cluster]                     VARCHAR (10)   NULL,
    [num_apuestas_artes_marciales_cluster]               INT            NULL,
    [ratio_apuestas_artes_marciales_cluster]             VARCHAR (10)   NULL,
    [ratio_apuestas_artes_marciales_total]               VARCHAR (10)   NULL,
    [num_visitas_artes_marciales_cluster]                INT            NULL,
    [ratio_visitas_artes_marciales_cluster]              VARCHAR (10)   NULL,
    [num_apuestas_boxeo_cluster]                         INT            NULL,
    [ratio_apuestas_boxeo_cluster]                       VARCHAR (10)   NULL,
    [ratio_apuestas_boxeo_total]                         VARCHAR (10)   NULL,
    [num_visitas_boxeo_cluster]                          INT            NULL,
    [ratio_visitas_boxeo_cluster]                        VARCHAR (10)   NULL,
    [num_apuestas_dardos_cluster]                        INT            NULL,
    [ratio_apuestas_dardos_cluster]                      VARCHAR (10)   NULL,
    [ratio_apuestas_dardos_total]                        VARCHAR (10)   NULL,
    [num_visitas_dardos_cluster]                         INT            NULL,
    [ratio_visitas_dardos_cluster]                       VARCHAR (10)   NULL,
    [num_apuestas_esports_cluster]                       INT            NULL,
    [ratio_apuestas_esports_cluster]                     VARCHAR (10)   NULL,
    [ratio_apuestas_esports_total]                       VARCHAR (10)   NULL,
    [num_visitas_esports_cluster]                        INT            NULL,
    [ratio_visitas_esports_cluster]                      VARCHAR (10)   NULL,
    [num_apuestas_hockey_cluster]                        INT            NULL,
    [ratio_apuestas_hockey_cluster]                      VARCHAR (10)   NULL,
    [ratio_apuestas_hockey_total]                        VARCHAR (10)   NULL,
    [num_visitas_hockey_cluster]                         INT            NULL,
    [ratio_visitas_hockey_cluster]                       VARCHAR (10)   NULL,
    [num_apuestas_loteria_cluster]                       INT            NULL,
    [ratio_apuestas_loteria_cluster]                     VARCHAR (10)   NULL,
    [ratio_apuestas_loteria_total]                       VARCHAR (10)   NULL,
    [num_visitas_loteria_cluster]                        INT            NULL,
    [ratio_visitas_loteria_cluster]                      VARCHAR (10)   NULL,
    [num_apuestas_politica_cluster]                      INT            NULL,
    [ratio_apuestas_politica_cluster]                    VARCHAR (10)   NULL,
    [ratio_apuestas_politica_total]                      VARCHAR (10)   NULL,
    [num_visitas_politica_cluster]                       INT            NULL,
    [ratio_visitas_politica_cluster]                     VARCHAR (10)   NULL
);


GO
CREATE NONCLUSTERED INDEX [name_clusterizacion]
    ON [dbo].[clusters]([name_clusterizacion] ASC);


GO
CREATE NONCLUSTERED INDEX [name_cluster]
    ON [dbo].[clusters]([name_cluster] ASC);


